baseURL = "https://rinablmz.netlify.app/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Marina Bluma"
theme = "dimension"
googleAnalytics = "G-BD51CG8DSH"

[params]
    author = "Marina Bluma"
    description = "Marina Bluma's personal site"
    copyrightPublishYear = "2021"
    copyrightText = " Template by Dmitry Pechnikov. Tuning and photos by Marina Bluma"
    disableLogo = false
     logoImage = "brain_white.png"
    # logoIcon = "gem"
     titleFontSize = "3.25rem"
     subtitleFontSize = "1.0rem"
    baseFontSize = "1rem"
    # overlayOpacityPercentage = "50"
    # disableImageOverlay = false
    modalWidth = "70rem"

    # customCSS = "custom.css"


[languages]
    [languages.en]
        languageName = "English"
        weight = 1

    [languages.ru]
        languageName = "Russian"
        weight = 2
        title = "Marina Bluma's personal site"
        [languages.ru.params]
            author = "Marina Bluma"
            description = "Не взлетим,так поплаваем"


[permalinks]
    "" = "/#:filename"
