baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Marina Bluma"
theme = "dimension"
# googleAnalytics = "UA-123-45"

[params]
    author = "Marina Bluma"
    description = "Personal site of Marina Bluma."
    copyrightPublishYear = "2021"
    copyrightText = " Template by Dmitry Pechnikov. Tuning and photos by Marina Bluma"
    disableLogo = false
     logoImage = "brain_white.png"
    # logoIcon = "gem"
     titleFontSize = "3.25rem"
     subtitleFontSize = "3.8rem"
    baseFontSize = "2rem"
    # overlayOpacityPercentage = "50"
    # disableImageOverlay = false
    modalWidth = "80rem"

    # customCSS = "custom.css"


[languages]
    [languages.en]
        languageName = "English"
        weight = 1

    [languages.ru]
        languageName = "Russian"
        weight = 2
        title = "My personal site"
        [languages.ru.params]
            author = "Marina Bluma"
            description = "Возможно. Вам это снится"


[permalinks]
    "" = "/#:filename"
